name: Update Exchange Rates

on:
  schedule:
    - cron: '*/15 * * * *' # Se ejecuta cada 20 minutos en punto (0, 20, 40)
  workflow_dispatch:      # Para pruebas manuales

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run scraper
        run: python main.py

      - name: Commit and Push
        run: |
          git config --global user.name "Bot de Tasas"
          git config --global user.email "bot@github.com"
          git add data/
          git commit -m "Actualización automática: $(date)" || exit 0
          git push
